extends:
    - eslint:recommended
    - plugin:@typescript-eslint/recommended
    - plugin:react/recommended
plugins:
    - import
root: true
rules:
    "@typescript-eslint/explicit-module-boundary-types": 0
    "@typescript-eslint/no-explicit-any": 0
    "@typescript-eslint/no-namespace": [ 2, { "allowDeclarations": true } ] # We declare namespaces for host site APIs.
    "@typescript-eslint/no-unused-vars": [ 2, { "argsIgnorePattern": "^_" } ]
    "import/order": [
        error,
        {
            alphabetize: { order: asc },
            groups: [ builtin, external, internal, parent, sibling ],
            newlines-between: always,
            pathGroups: [
                {
                    pattern: ~src/**,
                    group: internal,
                },
            ],
        },
    ]
    "indent": [ error, 4, { SwitchCase: 1 } ]
    "no-duplicate-imports": [ "error", { "includeExports": true } ]
    "no-unused-vars": 0 # Should be turned off when using @typescript-eslint.
    "react/display-name": 0
    "react/jsx-key": 0
    "react/no-unknown-property": [0, { ignore: ["class"] }]
    "semi": [ 2, "always" ]
settings:
    react:
        pragma: h
        version: latest
