extends:
    - eslint:recommended
    - plugin:@typescript-eslint/recommended
    - plugin:react/recommended
plugins:
    - import
root: true
rules:
    "@typescript-eslint/explicit-module-boundary-types": 0
    "@typescript-eslint/no-explicit-any": 0
    "@typescript-eslint/no-namespace": [ 2, { "allowDeclarations": true } ] # We declare namespaces for host site APIs.
    "@typescript-eslint/no-unused-vars": 0
    "arrow-spacing": [ error, { before: true, after: true } ]
    "block-spacing": [ error, always ]
    "comma-style": [ error, last ]
    "import/order": [
        error,
        {
            alphabetize: { order: asc },
            groups: [ builtin, external, internal, parent, sibling ],
            newlines-between: always,
            pathGroups: [
                {
                    pattern: ~src/**,
                    group: internal,
                },
            ],
        },
    ]
    "indent": [ error, 4, { SwitchCase: 1 } ]
    "key-spacing": [ error, { beforeColon: false, afterColon: true, mode: minimum } ]
    "keyword-spacing": [ error, { before: true, after: true } ]
    "no-constant-condition": error
    "no-duplicate-imports": [ "error", { "includeExports": true } ]
    "no-unused-vars": 0 # Should be turned off when using @typescript-eslint.
    "no-var": error
    "prefer-const": error
    "react/display-name": 0
    "react/jsx-key": 0
    "react/no-unknown-property": [0, { ignore: ["class"] }]
    "semi-spacing": [ error, { before: false, after: true } ]
    "semi": [ 2, "always" ]
    "spaced-comment": [ error, always ]
settings:
    react:
        pragma: h
        version: latest
