name: Validation

on:
  # CI workflow is responsible for building on push to master.
  pull_request:
    branches:
      - master

jobs:
  validation:
    name: Validation Build
    runs-on: ubuntu-latest
    steps:
      - name: Set time zone
        uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Europe/Stockholm"
      - uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 22.14.0
      - name: Install dependencies
        run: |
          npm ci
      - name: Test
        run: |
          npm test
      - name: Lint
        run: |
          npm run lint
      - name: Build (development)
        run: |
          npm run build
        env:
          CI: true
          USERSCRIPTER_VERBOSE: true
      - name: Build (production)
        run: |
          npm run build
        env:
          CI: true
          USERSCRIPTER_MODE: production
          USERSCRIPTER_VERBOSE: true
